### ISSUE TITLE
Menu Shows wrong stats for trees

### ISSUE THREAD

**Issue by Gariot** [Royal-Modding/FS19_InfoDisplay#2]
Hi! 

Thank you for your mod and your hard work! :)

I just wanted to let you know that the info showed for trees are wrong. First the sell price.  It may be a map thing or even depends on difficulty, but the prices the info menu shows, are wrong.

Then the woodchip info. Again, this might be a map thing (?). But when i tested it with vanilla equipment, the info was about 1800 litre off.

I had several mods loaded, but none should change anything on the tree price or woodchip amount. 
But if you want, i can test it with just the info mod loaded on a vanilla map.

Have a nice day! :)

**Comment by TyKonKet** [comment]
First of all, thank you too much to help us improve our mods.
To be honest we never tested if the "wood chips estimation" was right, we will give it a look and fix it if needed.
However we tested the wood sell price deeply and in all our tests it was right with all "economy difficulty" settings.
Obviously we will test it again now that you are reporting an issue with it.
Just one more info that could help troubleshooting, did you noticed this issues on MP or SP?

**Comment by Gariot** [comment]
Hey, thanks for the reply.

I tested it on singleplayer. To give you more information i will test everything again later on a vanilla map and with only your mod. Thinking about it, my wood sellpoint is a seperate mod and may have its own calculation for woodprices.

**Comment by TyKonKet** [comment]
Ok thanks, let me know 👍🏻

**Comment by Gariot** [comment]
Alright, i tested it on one of the standart maps with just this mod.

I cut down a tree, more or less halfed it, checked the price of one half and sold it. I got exactly double of what the mod said. Then i chopped the other half to woodchips and checked what the mod said and what i actually got. I think the mod said something about 1600 litre and in the end i got around 7000 litre.

Now its probably your turn to reproduce what i found :D

**Comment by TyKonKet** [comment]
Hi @Gariot, there are some news:
 - The issue with the wood sell price should be now  fixed.
 - The issue with wood chips amount have been only partially fixed, for more details you can read the description of https://github.com/Royal-Modding/FS19_InfoDisplay/commit/c970b08d905309fc4b004f5e6ecdeb74388a26e2

If you want to give it a try, you can download the latest RC release [here](https://github.com/Royal-Modding/FS19_InfoDisplay/releases/tag/1.2.0.0-RC1), let me know.
